"""Public library API for the FT Test Case Agent."""

from test_case_agent.api import (
    DEFAULT_MAX_CHARS,
    InvalidSourceError,
    NoMatchingSectionsError,
    OoxmlCoverageAudit,
    OoxmlSource,
    SourceFileEntry,
    SourceManifest,
    RequirementRegistry,
    RequirementRegistryEntry,
    SourceAnchor,
    build_requirements_registry,
    build_source_manifest,
    compute_file_sha256,
    compute_requirement_text_hash,
    inspect_source_quality,
    extract_ooxml_source_nodes,
    inspect_ooxml_coverage,
    load_requirements_registry,
    load_requirements_registry_jsonl,
    load_source_manifest,
    load_ooxml_source,
    load_sections,
    make_req_uid,
    preview_chunks,
    resolve_sections,
    SourceNode,
    write_requirements_registry,
    write_source_manifest,
)
from test_case_agent.models import Section, SectionChunk
from test_case_agent.source_quality import (
    SourceQualityIssue,
    analyze_sections,
    classify_source_quality_issue,
)

__all__ = [
    "DEFAULT_MAX_CHARS",
    "InvalidSourceError",
    "NoMatchingSectionsError",
    "OoxmlCoverageAudit",
    "OoxmlSource",
    "RequirementRegistry",
    "RequirementRegistryEntry",
    "Section",
    "SectionChunk",
    "SourceAnchor",
    "SourceFileEntry",
    "SourceManifest",
    "SourceNode",
    "SourceQualityIssue",
    "analyze_sections",
    "build_requirements_registry",
    "build_source_manifest",
    "classify_source_quality_issue",
    "compute_file_sha256",
    "compute_requirement_text_hash",
    "extract_ooxml_source_nodes",
    "inspect_ooxml_coverage",
    "inspect_source_quality",
    "load_requirements_registry",
    "load_requirements_registry_jsonl",
    "load_source_manifest",
    "load_ooxml_source",
    "load_sections",
    "make_req_uid",
    "preview_chunks",
    "resolve_sections",
    "write_requirements_registry",
    "write_source_manifest",
]
